server:
  port: 8080
spring:
  security:
    user:
      name: ${SECURITY_USERNAME:gold}
      password: ${SECURITY_PASSWORD:gold&pay}
  application:
    name: challenge-crud-pix
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: gold&pay
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true